
//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Admin.Models
{

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("aspnet_UsersInRolesView")]
    public partial class aspnet_UsersInRolesView
    {
        public System.DateTime CreateDate { get; set; }
        public string Email { get; set; }
        [Key, Column(Order = 1)]
        public Guid RoleId { get; set; }
        public string RoleName { get; set; }
        [Key, Column(Order = 0)]
        public Guid UserId { get; set; }
        public string UserName { get; set; }

    }
}