
//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Admin.Models
{

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("SenCompany")]
    public partial class SenCompany
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int CompanyId { get; set; }
        public string Address { get; set; }
        public string Comment { get; set; }
        public string ConnectionString { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }

        public string Description { get; set; }
        public string Email { get; set; }
        public string FaxNumber { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsLockedOut { get; set; }
        public string Logo { get; set; }
        public string Name { get; set; }
        public Nullable<int> PackageId { get; set; }
        public string TaxCode { get; set; }
        public string Telephone { get; set; }
        public Nullable<Guid> UserId { get; set; }
        public string Website { get; set; }


        public virtual vw_aspnet_MembershipUsers UserProfile { get; set; }

        public virtual SenPackage SenPackage { get; set; }

    }
}
