
//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Admin.Models
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("SenContract")]
    public partial class SenContract
    {

        public SenContract()
        {
            this.SenContractCashs = new HashSet<SenContractCash>();
            this.SenCommissions = new HashSet<SenCommission>(); 
        }


        [Key]
        public int ContractId { get; set; }
        public decimal Amount { get; set; }
        [ForeignKey("Assign")]
        public Nullable<Guid> AssignedTo { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public Nullable<decimal> CommissionPayment { get; set; }
        public Nullable<decimal> CommissionPercentage { get; set; }
        public Nullable<decimal> CommissionReceived { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public decimal ContractAmount { get; set; }
        public System.DateTime ContractDate { get; set; }
        public string ContractNumber { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        [ForeignKey("SenCustomer")]
        public Nullable<int> CustomerId { get; set; }
        public decimal Discount { get; set; }
        public Nullable<decimal> DiscountPercenttage { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public string Note { get; set; }
        public decimal Payment { get; set; }
        [ForeignKey("SenProduct")]
        public Nullable<int> ProductId { get; set; }

        public Nullable<int> Status { get; set; }



        public virtual vw_aspnet_MembershipUsers Assign { get; set; }
        public virtual SenCustomer SenCustomer { get; set; }
        public virtual SenProduct SenProduct { get; set; }


        public virtual ICollection<SenContractCash> SenContractCashs { get; set; }
        public virtual ICollection<SenCommission> SenCommissions { get; set; }
          
    }
}