//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Admin.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("SenChatMessage")]
    public partial class SenChatMessage
    {

        [Key]
        public int Id { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Content { get; set; }
        public string IpAddress { get; set; }
        public string UserId { get; set; }
        public string RefUserId { get; set; }
        public bool IsRead { get; set; }

    }
}