//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Admin.Models
{

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("SenGiftCard")]
    public partial class SenGiftCard
    {
        [Key]
        public int Id { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
        public string GiftCardCouponCode { get; set; }
        public int GiftCardTypeId { get; set; }
        public bool IsGiftCardActivated { get; set; }
        public bool IsRecipientNotified { get; set; }
        public string Message { get; set; }
        public string RecipientEmail { get; set; }
        public string RecipientName { get; set; }
        public string SenderEmail { get; set; }
        public string SenderName { get; set; }
        public Nullable<int> UserCashId { get; set; }

        public virtual SenUserCash SenUserCashs { get; set; }

    }
}