
//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Admin.Models
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("SenProduct")]
    public partial class SenProduct
    {
        public SenProduct()
        {
            this.SenContracts = new HashSet<SenContract>();
        }

        [Key]
        public int ProductId { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public string ProductCode { get; set; }

        public virtual ICollection<SenContract> SenContracts { get; set; }

    }
}