//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Admin.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("SenPackageLine")]
    public partial class SenPackageLine
    {
        [Key]
        public int PackageLineId { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public int PackageId { get; set; }
        public string Value { get; set; }

    }
}