//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Admin.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("SenPackageLineView")]
    public partial class SenPackageLineView
    {
        public int ApplicationId { get; set; }
        public string ApplicationName { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public string PackageDescription { get; set; }
        public int PackageId { get; set; }
        [Key]
        public int PackageLineId { get; set; }
        public string PackageName { get; set; }
        public string Value { get; set; }

    }
}