//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Admin.Models
{

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("SenPrivateMessageView")]
    public partial class SenPrivateMessageView
    {
        public System.DateTime CreatedOnUtc { get; set; }
        public Guid FromUserId { get; set; }
        public string FromUserName { get; set; }
        public bool IsDeletedByAuthor { get; set; }
        public bool IsDeletedByRecipient { get; set; }
        public bool IsRead { get; set; }
        [Key]
        public int PrivateMessageId { get; set; }
        public string Subject { get; set; }
        public string Text { get; set; }
        public Guid ToUserId { get; set; }
        public string ToUserName { get; set; }

    }
}