
//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Admin.Models
{

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("SenServiceView")]
    public partial class SenServiceView
    {
        public string Address { get; set; }
        public int ApplicationId { get; set; }
        public string ApplicationName { get; set; }
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Email { get; set; }
        public string FaxNumber { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsLockedOut { get; set; }
        public Nullable<int> PackageId { get; set; }
        public string PackageName { get; set; }
        [Key]
        public int ServiceId { get; set; }
        public string TaxCode { get; set; }
        public string Telephone { get; set; }
        public string UserEmail { get; set; }
        public Guid UserId { get; set; }
        public Nullable<Guid> UserIdCreated { get; set; }
        public string UserName { get; set; }
        public string UserNameCreated { get; set; }
        public string Website { get; set; }

    }
}