
//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Admin.Models
{

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("SenUserCash")]
    public partial class SenUserCash
    {
        [Key]
        public int UserCashId { get; set; }
        public decimal Amount { get; set; }
        public int CashType { get; set; }
        public Nullable<Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Description { get; set; }
        public Nullable<Guid> UserId { get; set; }
        public System.DateTime VoucherDate { get; set; }

    }
}