
//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Admin.Models
{

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("SenUserView")]
    public partial class SenUserView
    {
        public string Address { get; set; }
        public Nullable<decimal> AmountBalance { get; set; }
        public Nullable<Guid> ApplicationId { get; set; }
        public string Avatar { get; set; }
        public string FullName { get; set; }
        public Nullable<bool> IsAnonymous { get; set; }
        public Nullable<System.DateTime> LastActivityDate { get; set; }
        public Nullable<System.DateTime> LastPayment { get; set; }
        public string LoweredUserName { get; set; }
        public string MobileAlias { get; set; }

        public int SenUserId { get; set; }
        public string Telephone { get; set; }
        [Key]
        public Guid UserId { get; set; }
        public string UserName { get; set; }

    }
}