//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Admin.Models
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("vw_aspnet_MembershipUsers")]
    public partial class vw_aspnet_MembershipUsers
    {

        public vw_aspnet_MembershipUsers()
        {
            this.SenContracts = new HashSet<SenContract>();
            this.SenCompanys = new HashSet<SenCompany>();
            this.SenCustomers = new HashSet<SenCustomer>();
        }

        public Guid ApplicationId { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreateDate { get; set; }

       
        public string Email { get; set; }

        public int FailedPasswordAnswerAttemptCount { get; set; }
        public System.DateTime FailedPasswordAnswerAttemptWindowStart { get; set; }
        public int FailedPasswordAttemptCount { get; set; }
        public System.DateTime FailedPasswordAttemptWindowStart { get; set; }
        public bool IsAnonymous { get; set; }
        public bool IsApproved { get; set; }
        public bool IsLockedOut { get; set; }
        public System.DateTime LastActivityDate { get; set; }
        public System.DateTime LastLockoutDate { get; set; }
        public System.DateTime LastLoginDate { get; set; }
        public System.DateTime LastPasswordChangedDate { get; set; }
        public string LoweredEmail { get; set; }
        public string MobileAlias { get; set; }
        public string MobilePIN { get; set; }
        public string PasswordAnswer { get; set; }
        public int PasswordFormat { get; set; }
        public string PasswordQuestion { get; set; }

        [Key]
        [ForeignKey("SenUserView")]
        public Guid UserId { get; set; }
        public string UserName { get; set; }

        [NotMapped]
        public virtual string[] SelectedUserRoles { get; set; }

        [NotMapped]
        public virtual List<aspnet_Roles> Roles { get; set; }


        public virtual SenUserView SenUserView { get; set; }

        
        public virtual ICollection<SenContract> SenContracts { get; set; }

        public virtual ICollection<SenCompany> SenCompanys { get; set; }

        [ForeignKey("AssignedTo")]
        public virtual ICollection<SenCustomer> SenCustomers { get; set; }

        //public virtual ICollection<SenQueuedEmail> SenQueuedEmails { get; set; }

    }
}