
//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("AppAccumulatedMaterialView")]
    public partial class AppAccumulatedMaterialView
    {
        public System.DateTime AccumulatedDate { get; set; }
        [Key]
        public int AccumulatedMaterialID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> AmountFC { get; set; }
        public string ConstructionCode { get; set; }
        public int ConstructionID { get; set; }
        public string ConstructionName { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string ExpenseCode { get; set; }
        public Nullable<int> ExpenseID { get; set; }
        public string ExpenseName { get; set; }
        public bool IsActive { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public Nullable<decimal> Quantity { get; set; }

    }
}