//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("AppAccountTable")]
    public partial class AppAccountTable
    {
        public AppAccountTable()
        {
            //this.AppAccountBalanceTables = new HashSet<AppAccountBalanceTable>();
            //this.AppBankAccountTables = new HashSet<AppBankAccountTable>();
            //this.AppConstructionBalanceTables = new HashSet<AppConstructionBalanceTable>();
            //this.AppCustomerBalanceTables = new HashSet<AppCustomerBalanceTable>();
            //this.AppCustomerTables = new HashSet<AppCustomerTable>();
            //this.AppEmployeeBalanceTables = new HashSet<AppEmployeeBalanceTable>();
            //this.AppFcExchangeRateTables = new HashSet<AppFcExchangeRateTable>();
            //this.AppItemBalanceTables = new HashSet<AppItemBalanceTable>();
            //this.AppProductCostTables = new HashSet<AppProductCostTable>();
            //this.AppProductJournalTables = new HashSet<AppProductJournalTable>();
            //this.AppUnFinishedCostFactorTables = new HashSet<AppUnFinishedCostFactorTable>();
        }
        [Key]
        public int AccountID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string DisplayNumber { get; set; }
        public string Name { get; set; }
        public bool IsAccountObject { get; set; }
        public bool IsAccountLedger { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
    
        //public virtual ICollection<AppAccountBalanceTable> AppAccountBalanceTables { get; set; }
        //public virtual ICollection<AppBankAccountTable> AppBankAccountTables { get; set; }
        //public virtual ICollection<AppConstructionBalanceTable> AppConstructionBalanceTables { get; set; }
        //public virtual ICollection<AppCustomerBalanceTable> AppCustomerBalanceTables { get; set; }
        //public virtual ICollection<AppCustomerTable> AppCustomerTables { get; set; }
        //public virtual ICollection<AppEmployeeBalanceTable> AppEmployeeBalanceTables { get; set; }
        //public virtual ICollection<AppFcExchangeRateTable> AppFcExchangeRateTables { get; set; }
        //public virtual ICollection<AppItemBalanceTable> AppItemBalanceTables { get; set; }
        //public virtual ICollection<AppProductCostTable> AppProductCostTables { get; set; }
        //public virtual ICollection<AppProductJournalTable> AppProductJournalTables { get; set; }
        //public virtual ICollection<AppUnFinishedCostFactorTable> AppUnFinishedCostFactorTables { get; set; }
    }
}
