//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;


    [Table("AppCustomerGroupTable")]
    public partial class AppCustomerGroupTable
    {
        public AppCustomerGroupTable()
        {
            //this.AppCustomerTables = new HashSet<AppCustomerTable>();
        }
    
        [Key]
        public int CustomerGroupID { get; set; }
        public string CustomerGroupCode { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public Nullable<int> SalesPriceGroupID { get; set; }
    
        //public virtual AppSalesPriceGroupTable AppSalesPriceGroupTable { get; set; }
        //public virtual ICollection<AppCustomerTable> AppCustomerTables { get; set; }
    }
}
