//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;


    [Table("AppCustomerView")]
    public partial class AppCustomerView
    {
        [Key]
        public int CustomerID { get; set; }
        public string CustomerCode { get; set; }
        public string Name { get; set; }
        public string Contact { get; set; }
        public string Address { get; set; }
        public string TelephoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string TaxCode { get; set; }
        public string EmailAddress { get; set; }
        public string WebPage { get; set; }
        public Nullable<int> CustomerGroupID { get; set; }
        public bool IsCustomer { get; set; }
        public bool IsSupplier { get; set; }
        public bool IsEmployee { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public Nullable<int> DueDate { get; set; }
        public Nullable<int> DebtDate { get; set; }
        public Nullable<decimal> DebtLimit { get; set; }
        public string BankAccount { get; set; }
        public Nullable<int> AccountID { get; set; }
        public string DisplayNumber { get; set; }
        public string CustomerGroupCode { get; set; }
        public string CustomerGroupName { get; set; }
        public string Country { get; set; }
        public string StateProvince { get; set; }
        public string District { get; set; }
    }
}
