//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;


    [Table("AppCustomerTable")]
    public partial class AppCustomerTable
    {
        public AppCustomerTable()
        {
            //this.AppConstructionBalanceTables = new HashSet<AppConstructionBalanceTable>();
            //this.AppCustomerBalanceTables = new HashSet<AppCustomerBalanceTable>();
            //this.AppDocumentTables = new HashSet<AppDocumentTable>();
            //this.AppEmployeeBalanceTables = new HashSet<AppEmployeeBalanceTable>();
            //this.AppPurchaseContractTables = new HashSet<AppPurchaseContractTable>();
            //this.AppPurchasePriceTables = new HashSet<AppPurchasePriceTable>();
            //this.AppSaleContractTables = new HashSet<AppSaleContractTable>();
            //this.AppSalesPriceTables = new HashSet<AppSalesPriceTable>();
        }
    
        [Key]
        public int CustomerID { get; set; }
        public string CustomerCode { get; set; }
        public string Name { get; set; }
        public string Contact { get; set; }
        public string Address { get; set; }
        public string TelephoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string TaxCode { get; set; }
        public string EmailAddress { get; set; }
        public string WebPage { get; set; }
        public Nullable<int> CustomerGroupID { get; set; }
        public bool IsCustomer { get; set; }
        public bool IsSupplier { get; set; }
        public bool IsEmployee { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public Nullable<int> DueDate { get; set; }
        public Nullable<decimal> DebtLimit { get; set; }
        public Nullable<int> DebtDate { get; set; }
        public string BankAccount { get; set; }
        public Nullable<int> AccountID { get; set; }
        public string Country { get; set; }
        public string StateProvince { get; set; }
        public string District { get; set; }
    
        //public virtual AppAccountTable AppAccountTable { get; set; }
        //public virtual ICollection<AppConstructionBalanceTable> AppConstructionBalanceTables { get; set; }
        //public virtual ICollection<AppCustomerBalanceTable> AppCustomerBalanceTables { get; set; }
        //public virtual AppCustomerGroupTable AppCustomerGroupTable { get; set; }
        //public virtual ICollection<AppDocumentTable> AppDocumentTables { get; set; }
        //public virtual ICollection<AppEmployeeBalanceTable> AppEmployeeBalanceTables { get; set; }
        //public virtual ICollection<AppPurchaseContractTable> AppPurchaseContractTables { get; set; }
        //public virtual ICollection<AppPurchasePriceTable> AppPurchasePriceTables { get; set; }
        //public virtual ICollection<AppSaleContractTable> AppSaleContractTables { get; set; }
        //public virtual ICollection<AppSalesPriceTable> AppSalesPriceTables { get; set; }
    }
}
