//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("AppCustomerTemporaryTable")]
    public partial class AppCustomerTemporaryTable
    {
        [Key]
        public int CustomerID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public string Address { get; set; }
        public string BankAccount { get; set; }
        public string Contact { get; set; }
        public string Country { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string CustomerCode { get; set; }
        public Nullable<int> CustomerGroupID { get; set; }
        public Nullable<int> DebtDate { get; set; }
        public Nullable<decimal> DebtLimit { get; set; }
        public string District { get; set; }
        public Nullable<int> DueDate { get; set; }
        public string EmailAddress { get; set; }
        public string FaxNumber { get; set; }
        public bool IsActive { get; set; }
        public bool IsCustomer { get; set; }
        public bool IsEmployee { get; set; }
        public bool IsSupplier { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public string StateProvince { get; set; }
        public string TaxCode { get; set; }
        public string TelephoneNumber { get; set; }
        public string WebPage { get; set; }

    }
}