//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("AppCurrencyTable")]
    public partial class AppCurrencyTable
    {
        public AppCurrencyTable()
        {
            //this.AppDocumentTables = new HashSet<AppDocumentTable>();
            //this.AppPurchaseContractTables = new HashSet<AppPurchaseContractTable>();
            //this.AppSaleContractTables = new HashSet<AppSaleContractTable>();
            this.IsActive = true;
        }
    
        [Key]
        public int CurrencyID { get; set; }
        public string IsoCode { get; set; }
        public string Symbol { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
    
        //public virtual ICollection<AppDocumentTable> AppDocumentTables { get; set; }
        //public virtual ICollection<AppPurchaseContractTable> AppPurchaseContractTables { get; set; }
        //public virtual ICollection<AppSaleContractTable> AppSaleContractTables { get; set; }
    }
}
