
//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("AppDocumentVATTempTable")]
    public partial class AppDocumentVATTempTable
    {
        [Key]
        public long DocumentVATID { get; set; }
        public Nullable<int> AccountCreditLineID { get; set; }
        public Nullable<int> AccountDebitLineID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> AmountFC { get; set; }
        public Nullable<decimal> AmountVAT { get; set; }
        public Nullable<decimal> AmountVATFC { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerName { get; set; }
        public string DescriptionVAT { get; set; }
        public Nullable<long> DocumentID { get; set; }
        public int DocumentVATType { get; set; }
        public Nullable<System.DateTime> ExDate01 { get; set; }
        public Nullable<System.DateTime> ExDate02 { get; set; }
        public Nullable<System.DateTime> ExDate03 { get; set; }
        public Nullable<System.DateTime> ExDate04 { get; set; }
        public Nullable<System.DateTime> ExDate05 { get; set; }
        public Nullable<System.DateTime> ExDate06 { get; set; }
        public Nullable<decimal> ExNumeric01 { get; set; }
        public Nullable<decimal> ExNumeric02 { get; set; }
        public Nullable<decimal> ExNumeric03 { get; set; }
        public Nullable<decimal> ExNumeric04 { get; set; }
        public Nullable<decimal> ExNumeric05 { get; set; }
        public Nullable<decimal> ExNumeric06 { get; set; }
        public Nullable<decimal> ExNumeric07 { get; set; }
        public Nullable<decimal> ExNumeric08 { get; set; }
        public Nullable<decimal> ExNumeric09 { get; set; }
        public Nullable<decimal> ExNumeric10 { get; set; }
        public Nullable<int> ExObject01ID { get; set; }
        public Nullable<int> ExObject02ID { get; set; }
        public Nullable<int> ExObject03ID { get; set; }
        public Nullable<int> ExObject04ID { get; set; }
        public Nullable<int> ExObject05ID { get; set; }
        public Nullable<int> ExObject06ID { get; set; }
        public Nullable<int> ExObject07ID { get; set; }
        public Nullable<int> ExObject08ID { get; set; }
        public Nullable<int> ExObject09ID { get; set; }
        public Nullable<int> ExObject10ID { get; set; }
        public Nullable<int> ExObject11ID { get; set; }
        public Nullable<int> ExObject12ID { get; set; }
        public Nullable<int> ExObject13ID { get; set; }
        public Nullable<int> ExObject14ID { get; set; }
        public Nullable<int> ExObject15ID { get; set; }
        public Nullable<int> ExObject16ID { get; set; }
        public Nullable<int> ExObject17ID { get; set; }
        public Nullable<int> ExObject18ID { get; set; }
        public Nullable<int> ExObject19ID { get; set; }
        public Nullable<int> ExObject20ID { get; set; }
        public string ExString01 { get; set; }
        public string ExString02 { get; set; }

        public string ExString03 { get; set; }
        public string ExString04 { get; set; }
        public string ExString05 { get; set; }
        public string ExString06 { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> PurchaseTaxID { get; set; }
        public Nullable<int> SalesTaxID { get; set; }
        public string TaxCode { get; set; }
        public Nullable<System.DateTime> VATDate { get; set; }
        public string VATNumber { get; set; }
        public string VATSerial { get; set; }
        public string VATTemplate { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public string VoucherNumber { get; set; }
    }
}