//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("AppExObject09View")]
    public partial class AppExObject09View
    {
        [Key]
        public int ExObject09ID { get; set; }
        public string ExObject09Code { get; set; }
        public string ExObject09Name { get; set; }
    }
}
