//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("AppEmployeeBalanceView")]
    public partial class AppEmployeeBalanceView
    {
        public AppEmployeeBalanceView()
        {
            this.BalanceDate = DateTime.Today;
        }

        public int AccountID { get; set; }
        public System.DateTime BalanceDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> CreditFC { get; set; }
        public string CustomerCode { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CustomerName { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> DebitFC { get; set; }
        public string DisplayNumber { get; set; }
        [Key]
        public int EmployeeBalanceID { get; set; }
        public string EmployeeCode { get; set; }
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }

    }
}