//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("AppEmployeeView")]
    public partial class AppEmployeeView
    {
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string BankAccount { get; set; }
        public string BankCode { get; set; }
        public Nullable<int> BankID { get; set; }
        public string BankName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Comments { get; set; }
        public string CountryCode { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string CountryName { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string DepartmentCode { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public string EducationLevelCode { get; set; }
        public Nullable<int> EducationLevelID { get; set; }
        public string EducationLevelName { get; set; }
        public string EmailAddress { get; set; }
        public string EmployeeCode { get; set; }
        [Key]
        public int EmployeeID { get; set; }
        public string EthnicCode { get; set; }
        public Nullable<int> EthnicID { get; set; }
        public string EthnicName { get; set; }
        public Nullable<int> Gender { get; set; }
        public string GenderName { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public byte[] Image { get; set; }
        public bool IsActive { get; set; }
        public string JobTitle { get; set; }
        public Nullable<System.DateTime> LastReviewDate { get; set; }
        public string Mobilephone { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public string Name { get; set; }
        public string NationalityCode { get; set; }
        public Nullable<int> NationalityID { get; set; }
        public string NationalityName { get; set; }
        public string PIN { get; set; }
        public string PINAddress { get; set; }
        public Nullable<System.DateTime> PINDate { get; set; }
        public string PositionCode { get; set; }
        public Nullable<int> PositionID { get; set; }
        public string PositionName { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string ReligionCode { get; set; }
        public Nullable<int> ReligionID { get; set; }
        public string ReligionName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }

        public string TaxCode { get; set; }
        public Nullable<int> TaxPIType { get; set; }
        public string TelephoneNumber { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserName { get; set; }
    }
}