//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("AppExObject05View")]
    public partial class AppExObject05View
    {
        [Key]
        public int ExObject05ID { get; set; }
        public string ExObject05Code { get; set; }
        public string ExObject05Name { get; set; }
    }
}
