//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;


    [Table("AppExObject20View")]
    public partial class AppExObject20View
    {
        [Key]
        public int ExObject20ID { get; set; }
        public string ExObject20Code { get; set; }
        public string ExObject20Name { get; set; }
    }
}
