//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;


    [Table("AppExObject17View")]
    public partial class AppExObject17View
    {
        [Key]
        public int ExObject17ID { get; set; }
        public string ExObject17Code { get; set; }
        public string ExObject17Name { get; set; }
    }
}
