
//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("AppFixedAssetLineTable")]
    public partial class AppFixedAssetLineTable
    {
        [Key]
        public int FixedAssetLineID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Amount2 { get; set; }
        public Nullable<decimal> AmountDepreciation { get; set; }
        public Nullable<decimal> AmountEnd { get; set; }
        public string DescriptionLine { get; set; }
        public int FixedAssetID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public string VoucherNumber { get; set; }

    }
}