
//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("AppItemGroupTable")]
    public partial class AppItemGroupTable
    {
        public AppItemGroupTable()
        {
            this.AppItemTables = new HashSet<AppItemView>();
        }


        public virtual ICollection<AppItemView> AppItemTables { get; set; }


        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public bool IsActive { get; set; }
        public string ItemGroupCode { get; set; }
        [Key]
        public int ItemGroupID { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public string Name { get; set; }

    }
}