

//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("AppItemOutputRateTable")]
        public partial class AppItemOutputRateTable
        {
            [Key]
            public int ItemOutputRateID { get; set; }
            public Nullable<decimal> Amount { get; set; }
            public Nullable<decimal> AmountFC { get; set; }
            public Nullable<int> CreatedBy { get; set; }
            public Nullable<System.DateTime> CreatedDateTime { get; set; }
            public System.DateTime DateOfExecution { get; set; }
            public Nullable<System.DateTime> ExpiryDate { get; set; }
            public Nullable<bool> IsActive { get; set; }
            public int ItemID { get; set; }
            public Nullable<int> ModifiedBy { get; set; }
            public Nullable<System.DateTime> ModifiedDateTime { get; set; }
            public int ProductID { get; set; }
            public Nullable<decimal> Quantity { get; set; }

        }
    }


