//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("AppItemMethodTypeTable")]
    public partial class AppItemMethodTypeTable
    {
        //public AppItemMethodTypeTable()
        //{
        //    this.AppItemTables = new HashSet<AppItemTable>();
        //}
    
        [Key]
        public int EnumValue { get; set; }
        public string EnumName { get; set; }
    
        //public virtual ICollection<AppItemTable> AppItemTables { get; set; }
    }
}
