
//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("AppSalesPriceLineTable")]
    public partial class AppSalesPriceLineTable
    {
        public int ItemID { get; set; }
        public Nullable<decimal> QuantityFrom { get; set; }
        public Nullable<decimal> QuantityTo { get; set; }
        public int SalesPriceGroupID { get; set; }
        [Key]
        public long SalesPriceLineID { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> UnitPriceFC { get; set; }

    }
}