//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("AppUnitOfMeasureLinkTable")]
    public partial class AppUnitOfMeasureLinkTable
    {
        public AppUnitOfMeasureLinkTable()
        {
            //this.AppBarcodeTables = new HashSet<AppBarcodeTable>();
            this.AppUnitOfMeasureRateTables = new HashSet<AppUnitOfMeasureRateTable>();
        }
        [Key]
        public int UOMLinkID { get; set; }
    
        //public virtual ICollection<AppBarcodeTable> AppBarcodeTables { get; set; }
        public virtual ICollection<AppUnitOfMeasureRateTable> AppUnitOfMeasureRateTables { get; set; }
    }
}
