//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("AppVCA01View")]
    public partial class AppVCA01View
    {
        public AppVCA01View()
        {
            this.AppVCA01LineViews = new HashSet<AppVCA01LineView>();
            this.AppVCA01VATViews = new HashSet<AppVCA01VATView>();

            this.VoucherDate = DateTime.Today;
            this.IsoCode = Services.Voucher.GetIsoCode();
            this.PostType = 0; // Trạng thái chứng từ 0: post tất cả vào sổ sách
            this.VoucherID = Services.Voucher.GetVoucherID("CA01");

            this.CurrencyID = Services.Voucher.GetCurrencyIDByIsoCode(this.IsoCode);
            this.ExchangeRate = Services.Voucher.GetExchangeRate(this.CurrencyID, this.VoucherDate);
            this.VoucherNumber = Services.Voucher.GetVoucherNumber(this.VoucherID);

        }
        public virtual ICollection<AppVCA01LineView> AppVCA01LineViews { get; set; }
        public virtual ICollection<AppVCA01VATView> AppVCA01VATViews { get; set; }

        public virtual ICollection<long> AppVCA01LineViewz { get; set; }
        public virtual ICollection<long> AppVCA01VATViewz { get; set; }

        [Key]
        public long DocumentID { get; set; }
        public Nullable<long> ParentID { get; set; }
        public int VoucherID { get; set; }
        public string VoucherCode { get; set; }
        public string VoucherName { get; set; }
        public int CurrencyID { get; set; }
        public string IsoCode { get; set; }
        public decimal ExchangeRate { get; set; }
        public System.DateTime VoucherDate { get; set; }
        public string VoucherNumber { get; set; }
        public string Description { get; set; }
        public Nullable<int> PostType { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public Nullable<int> AccountCreditID { get; set; }
        public string DisplayNumberCredit { get; set; }
        public Nullable<int> AccountDebitID { get; set; }
        public string DisplayNumberDebit { get; set; }
        public Nullable<decimal> SumAmountFC { get; set; }
        public Nullable<decimal> SumAmount { get; set; }
        public Nullable<decimal> SumAmountVATFC { get; set; }
        public Nullable<decimal> SumAmountVAT { get; set; }
        public Nullable<decimal> SumTotalFC { get; set; }
        public Nullable<decimal> SumTotal { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
    }
}
