

//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{
    using System;
    public partial class AppVSO01PrintView
    {

        public Nullable<int> AccountCreditID { get; set; }
        public Nullable<int> AccountCreditLineID { get; set; }
        public Nullable<int> AccountDebitID { get; set; }
        public Nullable<int> AccountDebitLineID { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> AmountFC { get; set; }
        public Nullable<decimal> AmountSell { get; set; }
        public Nullable<decimal> AmountSellFC { get; set; }
        public string Contact { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string CurrencyCompanyName { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public string CurrencyName { get; set; }
        public string CustomerCode { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string Description { get; set; }
        public string DescriptionLine { get; set; }
        public string DescriptionVAT { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> DiscountFC { get; set; }
        public Nullable<decimal> DiscountPercentage { get; set; }
        public string DisplayNumberCredit { get; set; }
        public string DisplayNumberDebit { get; set; }
        public string DisplayNumberLineCredit { get; set; }
        public string DisplayNumberLineDebit { get; set; }
        public Nullable<long> DocumentID { get; set; }
        public Nullable<long> DocumentLineID { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public string IsoCode { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> MeasureRate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public string NumberToWords { get; set; }
        public string NumberToWordsFC { get; set; }
        public Nullable<int> NumberVAT { get; set; }
        public Nullable<System.Int32> ParentID { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<int> PostType { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Quantity0 { get; set; }
        public Nullable<decimal> SumAmount { get; set; }
        public Nullable<decimal> SumAmountFC { get; set; }
        public Nullable<decimal> SumAmountSell { get; set; }
        public Nullable<decimal> SumAmountSellFC { get; set; }

        public Nullable<decimal> SumAmountVAT { get; set; }
        public Nullable<decimal> SumAmountVATFC { get; set; }
        public Nullable<decimal> SumDiscount { get; set; }
        public Nullable<decimal> SumDiscountFC { get; set; }
        public Nullable<decimal> SumTotal { get; set; }
        public Nullable<decimal> SumTotalFC { get; set; }
        public string TaxCode { get; set; }
        public string TelephoneNumber { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> UnitPriceFC { get; set; }
        public Nullable<decimal> UnitPriceSell { get; set; }
        public Nullable<decimal> UnitPriceSellFC { get; set; }
        public string UOMCode { get; set; }
        public Nullable<int> UOMID { get; set; }
        public Nullable<System.DateTime> VATDate { get; set; }
        public string VATNumber { get; set; }
        public string VATSerial { get; set; }
        public string VoucherCode { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public Nullable<int> VoucherID { get; set; }
        public string VoucherName { get; set; }
        public string VoucherNumber { get; set; }
        public string WarehouseLineCode { get; set; }
        public Nullable<int> WarehouseLineID { get; set; }
        public string WarehouseLineName { get; set; }
    }
}