//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("AppWarehouseTable")]
    public partial class AppWarehouseTable
    {
        public AppWarehouseTable()
        {
            //this.AppDocumentTables = new HashSet<AppDocumentTable>();
            //this.AppItemBalanceTables = new HashSet<AppItemBalanceTable>();
            this.ResTables = new HashSet<ResTable>();

        }


        public virtual ICollection<ResTable> ResTables { get; set; }

        [Key]
        public int WarehouseID { get; set; }
        public string WarehouseCode { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }


        //public virtual ICollection<AppDocumentTable> AppDocumentTables { get; set; }
        //public virtual ICollection<AppItemBalanceTable> AppItemBalanceTables { get; set; }
    }
}
