
//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("GapJournal")]
    public partial class GapJournal
    {
        public GapJournal()
        {
            //this.GapSeeds = new HashSet<GapSeed>();
        }

        public virtual ICollection<GapJournalCare> GapJournalCares { get; set; }
        public virtual ICollection<GapJournalHarvest> GapJournalHarvests { get; set; }

        [Key]
        public int JournalId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public int FieldId { get; set; }
        public System.DateTime HarvestDateBG { get; set; }
        public System.DateTime HarvestDateEnd { get; set; }
        public System.DateTime JournalDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public string Note { get; set; }
        public int SeedId { get; set; }
        public int StatusId { get; set; }
        public int TreeId { get; set; }

        public virtual GapField GapField { get; set; }
        public virtual GapTree GapTree { get; set; }

        public virtual GapSeed GapSeed { get; set; }

        public Nullable<System.DateTime> IsolationDate { get; set; }
        public Nullable<int> IsolationDay { get; set; }

        public DateTime IsolationDateEnd()
        {
            DateTime _result = new DateTime();
            if (this.IsolationDate.HasValue)
            {
                _result = this.IsolationDate.GetValueOrDefault().AddDays(this.IsolationDay.GetValueOrDefault());
            }
            return _result;
        }
    }
}