
//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("GapJournalCare")]
    public partial class GapJournalCare
    {
        [Key]
        public int JournalCareId { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string JobName { get; set; }
        public System.DateTime JournalCareDate { get; set; }
        public int JournalId { get; set; }
        public string Note { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<decimal> Quantity0 { get; set; }
        public Nullable<int> UOMID { get; set; }
        public Nullable<int> WorkID { get; set; }

        public virtual AppItemTable AppItemTable { get; set; }

        public virtual AppUnitOfMeasureTable AppUnitOfMeasureTable { get; set; }

        public virtual AppWorkTable AppWorkTable { get; set; }

    }
}