
//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("GapTree")]
    public partial class GapTree
    {
        public GapTree()
        {
            this.GapSeeds = new HashSet<GapSeed>();
        }

        public virtual AppItemTable AppItemTable{ get; set; }

        public virtual ICollection<GapSeed> GapSeeds { get; set; }

        [Key]
        public int TreeId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public bool IsActive { get; set; }

        [ForeignKey("AppItemTable")]
        public Nullable<int> RefItemID { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<decimal> QuantityExpected { get; set; }
        public Nullable<int> RefHarvestDateBG { get; set; }
        public Nullable<int> RefHarvestDateEnd { get; set; }


    }
}