
//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{

    using System;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("RpInventorySummaryMinMax")]
    public partial class RpInventorySummaryMinMax
    {
        public Nullable<int> AccountID { get; set; }
        public string AccountName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Amount2 { get; set; }
        public Nullable<decimal> AmountFC { get; set; }
        public Nullable<decimal> AmountFC2 { get; set; }
        public Nullable<decimal> AmountFCSBG { get; set; }
        public Nullable<decimal> AmountFCSEnd { get; set; }
        public Nullable<decimal> AmountSBG { get; set; }
        public Nullable<decimal> AmountSEnd { get; set; }
        public string DisplayNumber { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Quantity2 { get; set; }
        public Nullable<decimal> QuantityMax { get; set; }
        public Nullable<decimal> QuantityMin { get; set; }
        public Nullable<decimal> QuantitySBG { get; set; }
        public Nullable<decimal> QuantitySEnd { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> UnitPrice2 { get; set; }
        public Nullable<decimal> UnitPriceFC { get; set; }
        public Nullable<decimal> UnitPriceFC2 { get; set; }
        public Nullable<decimal> UnitPriceFCSBG { get; set; }
        public Nullable<decimal> UnitPriceFCSEnd { get; set; }
        public Nullable<decimal> UnitPriceSBG { get; set; }
        public Nullable<decimal> UnitPriceSEnd { get; set; }
        public string UOMCode { get; set; }
        public string WarehouseCode { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public string WarehouseName { get; set; }

    }
}