//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{

    using System;
    public partial class RpInventorySummaryOnlyQuantity
    {
        public Nullable<int> AccountID { get; set; }
        public string AccountName { get; set; }
        public string DisplayNumber { get; set; }
        public string ItemCode { get; set; }
        public string ItemGroupCode { get; set; }
        public Nullable<int> ItemGroupID { get; set; }
        public string ItemGroupName { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Quantity2 { get; set; }
        public Nullable<decimal> QuantitySBG { get; set; }
        public Nullable<decimal> QuantitySEnd { get; set; }
        public string UOMCode { get; set; }
        public string WarehouseCode { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public string WarehouseName { get; set; }

    }
}