//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{
    using System;
    public partial class RpInventorySummary
    {
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string ItemGroupCode { get; set; }
        public string ItemGroupName { get; set; }
        public string UOMCode { get; set; }
        public string DisplayNumber { get; set; }
        public string AccountName { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<decimal> QuantitySBG { get; set; }
        public Nullable<decimal> AmountSBG { get; set; }
        public Nullable<decimal> AmountFCSBG { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> AmountFC { get; set; }
        public Nullable<decimal> Quantity2 { get; set; }
        public Nullable<decimal> Amount2 { get; set; }
        public Nullable<decimal> AmountFC2 { get; set; }
        public Nullable<decimal> QuantitySEnd { get; set; }
        public Nullable<decimal> AmountSEnd { get; set; }
        public Nullable<decimal> AmountFCSEnd { get; set; }
        public Nullable<decimal> UnitPriceSBG { get; set; }
        public Nullable<decimal> UnitPriceFCSBG { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> UnitPriceFC { get; set; }
        public Nullable<decimal> UnitPrice2 { get; set; }
        public Nullable<decimal> UnitPriceFC2 { get; set; }
        public Nullable<decimal> UnitPriceSEnd { get; set; }
        public Nullable<decimal> UnitPriceFCSEnd { get; set; }
    }
}
