//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{

    using System;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("RpRevenueByItem")]
    public partial class RpRevenueByItem
    {
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> AmountFC { get; set; }
        public Nullable<decimal> AmountSell { get; set; }
        public Nullable<decimal> AmountSellFC { get; set; }
        public Nullable<decimal> DisCount { get; set; }
        public Nullable<decimal> DiscountFC { get; set; }
        public string ItemCode { get; set; }
        public string ItemGroupCode { get; set; }
        public Nullable<int> ItemGroupID { get; set; }
        public string ItemGroupName { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Revenue { get; set; }
        public Nullable<decimal> RevenueFC { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> UnitPriceFC { get; set; }
        public Nullable<decimal> UnitPriceSell { get; set; }
        public Nullable<decimal> UnitPriceSellFC { get; set; }
        public string UOMCode { get; set; }
        public Nullable<int> UOMID { get; set; }

    }
}