//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{

    using System;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("RpRevenueByCustomer")]
    public partial class RpRevenueByCustomer
    {
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> AmountFC { get; set; }
        public Nullable<decimal> AmountSell { get; set; }
        public Nullable<decimal> AmountSellFC { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerGroupCode { get; set; }
        public Nullable<int> CustomerGroupID { get; set; }
        public string CustomerGroupName { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CustomerName { get; set; }
        public Nullable<decimal> DisCount { get; set; }
        public Nullable<decimal> DiscountFC { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Revenue { get; set; }
        public Nullable<decimal> RevenueFC { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> UnitPriceFC { get; set; }
        public Nullable<decimal> UnitPriceSell { get; set; }
        public Nullable<decimal> UnitPriceSellFC { get; set; }

    }
}