//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{

    using System;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("RpTrialBalanceExpense")]
    public partial class RpTrialBalanceExpense
    {
        public Nullable<int> AccountID { get; set; }
        public string AccountName { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> CreditFC { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> DebitFC { get; set; }
        public string DisplayNumber { get; set; }

        public string ExpenseCode { get; set; }
        public Nullable<int> ExpenseID { get; set; }
        public string ExpenseName { get; set; }

    }
}