//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{

    using System;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("RpTrialBalance")]
    public partial class RpTrialBalance
    {
        public Nullable<int> AccountID { get; set; }
        public string AccountName { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> CreditFC { get; set; }
        public Nullable<decimal> CreditFCSBG { get; set; }
        public Nullable<decimal> CreditFCSEnd { get; set; }
        public Nullable<decimal> CreditSBG { get; set; }
        public Nullable<decimal> CreditSEnd { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> DebitFC { get; set; }
        public Nullable<decimal> DebitFCSBG { get; set; }
        public Nullable<decimal> DebitFCSEnd { get; set; }
        public Nullable<decimal> DebitSBG { get; set; }
        public Nullable<decimal> DebitSEnd { get; set; }
        public string DisplayNumber { get; set; }
        public string ParentDisplayNumber { get; set; }
        public Nullable<int> ParentID { get; set; }

    }
}