//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("SysBusiness")]
    public partial class SysBusiness
    {
        public string AssemblyName { get; set; }
        public string AssemblyTypeName { get; set; }
        [Key]
        public string BusinessCode { get; set; }
        public string Des { get; set; }
        public string TableUIList { get; set; }
        public Nullable<int> Type { get; set; }
    }
}


