//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("SysMenu")]
    public partial class SysMenu
    {
        public SysMenu()
        {
            //this.SysMenu1 = new HashSet<SysMenu>();
            //this.SysMenuRoles = new HashSet<SysMenuRole>();
        }
        [Key]
        public string MenuID { get; set; }
        public string ParentID { get; set; }
        public string Des { get; set; }
        public byte[] MenuIcon { get; set; }
        public Nullable<int> MenuOrder { get; set; }
        public Nullable<int> MenuType { get; set; }
        public string BusinessCode { get; set; }
        public string Note { get; set; }
        public bool IsActive { get; set; }

        //public virtual SysBusiness SysBusiness { get; set; }
        //public virtual ICollection<SysMenu> SysMenu1 { get; set; }
        //public virtual SysMenu SysMenu2 { get; set; }
        //public virtual ICollection<SysMenuRole> SysMenuRoles { get; set; }
    }
}
