//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("SysOption")]    
    public partial class SysOption
    {
        [Key]
        public int SysOptionID { get; set; }
        public string SysOptionName { get; set; }
        public string Type { get; set; }
        public string Des { get; set; }
        public string SysOptionValue { get; set; }
        public string SysOptionDefault { get; set; }
    }
}
