
//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("SysTable")]
    public partial class SysTable
    {
        [Key]
        public string TableName { get; set; }
        public string Des { get; set; }
        public int Type { get; set; }
        public bool UType { get; set; }

    }
}