//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Accounting.Models
{
    using System;

    public partial class wSalesModel
    {
        public int Year { get; set; }
        public int Month { get; set; }
        public Nullable<decimal> AmountSell { get; set; }
        //public Nullable<decimal> AmountSellFC { get; set; }
    }

    public partial class wAppAccountBalanceEnd
    {
        public int AccountID { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> CreditFC { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> DebitFC { get; set; }
    }
}
