
//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("Language")]
    public partial class Language
    {
        [Key]
        public int Id { get; set; }
        public int DisplayOrder { get; set; }
        public string FlagImageFileName { get; set; }
        public string LanguageCulture { get; set; }
        public string Name { get; set; }
        public bool Published { get; set; }
        public bool Rtl { get; set; }
        public string UniqueSeoCode { get; set; }

    }
}
