
//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("SenPrivateMessage")]
    public partial class SenPrivateMessage
    {
        [Key]
        public int PrivateMessageId { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }

        [ForeignKey("FromUser")]
        public Guid FromUserId { get; set; }
        public bool IsDeletedByAuthor { get; set; }
        public bool IsDeletedByRecipient { get; set; }
        public bool IsRead { get; set; }
        public string Subject { get; set; }
        public string Text { get; set; }

        [ForeignKey("ToUser")]
        public Guid ToUserId { get; set; }


        public virtual UserProfile FromUser { get; set; }
        public virtual UserProfile ToUser { get; set; }

    }
}