
//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("SenUserProfile")]
    public partial class SenUserProfile
    {
        [Key, Column(Order = 0)]
        public int SenUserId { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        [Key, Column(Order = 1)]
        public string PropertyName { get; set; }
        public string PropertyValue { get; set; }

    }
}