
//------------------------------------------------------------------------------
// <auto-generated>
// gen by lotusviet.vn
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("SysTableDetail")]
    public partial class SysTableDetail
    {
        [Key, Column(Order = 0)]
        public string TableName { get; set; }
        [Key, Column(Order = 1)]
        public string ColumnName { get; set; }
        public Nullable<bool> AllowDBNull { get; set; }
        public string CultureInfo { get; set; }
        public string DefaultValue { get; set; }
        public string Des { get; set; }
        public string FilterExpression { get; set; }
        public string FormatType { get; set; }
        public string FormatValue { get; set; }
        public Nullable<int> GridViewOrder { get; set; }
        public bool GridViewShow { get; set; }
        public Nullable<int> GridViewWidth { get; set; }
        public Nullable<bool> IsCarryDown { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public string OrderExpression { get; set; }
        public Nullable<bool> ReadOnly { get; set; }
        public string TableNameValid { get; set; }
        public bool UType { get; set; }

    }
}